[package]
name = "cynthia_con"
description = "A small output colorising/styling library originally created for the Cynthia project."
version = "0.1.0"
edition = "2021"
repository = "https://github.com/strawmelonjuice/cynthia_con"
license = "MIT"
[dependencies]
termsize = "0.1"
